### ISSUE TITLE
Allow to type the query outside of the component

### ISSUE THREAD

**Issue by Newbie012** [MedFlyt/eslint-plugin-graphql-type-checker#2]
Most of the time we write our queries outside of components. Something like:

```ts
import Apollo, { gql } from "@apollo/client";

const GET_PATIENT = gql`
  query {
    patient(id: 10) {
      firstName
    }
  }
`;

function PatientCard() {
  const { error, data, loading } = Apollo.useQuery(GET_PATIENT);

  return `<div className="App"></div>`;
}

```

Currently, we have to type all of the queries inside the components. Otherwise, the plugin won't throw an error.

I guess it would be a bit tricky due to the fact we allow multiple schemas. I think we should find a different approach since depending on the name of the object would limit us.

**Comment by Oblosys** [comment]
Since the plugin only matches on a syntactic level, it will not be able to annotate `Apollo.useQuery` here based on the type of `GET_PATIENT`, but it is possible to create a wrapper to convert the query to an `Apollo.TypedDocumentNode`.

Imagine a module `Wrap` that exports a function`query`, or for simplicity an object `Wrap` with a method `query`: 

```ts
const Wrap = {
  query<Res, Args>(gql: Apollo.DocumentNode): Apollo.TypedDocumentNode<Res, Args> {
    return gql;
  },
};
```

If you apply `Wrap.query` to `GET_PATIENT`, the plugin will be able to generate the type annotation:

```ts
//                            v-- generated by plugin --v
const GET_PATIENT = Wrap.query<{ firstName: string }, {}>(gql`
  query {
    patient(id: 10) {
      firstName
    }
  }
`);
```

The now correctly typed `GET_PATIENT` can simply be passed to `useQuery`:

```ts
export function PatientCard() {
  const {
    data, // inferred type: {firstName: string} | undefined
  } = useQuery(GET_PATIENT);

  return <div className="App"></div>;
}
```

[TypeScript playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcARFDvmQNwBQokscA3nACIS4CuIWAdjAByEACZY4AXzhES5AOZRkYABYBHADa0G4aPACCkDRogAaVnHmbz3VFgCK3LFACeUmcVJkAAsojGIAHpcDWABGG06XAh+VHgAdSUwOABeVjo4ODUnVwAebFRzfSh5VAA+AAorDQAuDi5ecJFxAEo6w38TADoAFRcwLFFOHj5BZqx8rEK4YtKy9MzMyhhuKH5LTXpMyVM6SXo6QMDFk9Oz88WANwBaa8sBZ2QYQbgAIzcwDW55YHXby6iMTicAA4gBRHoAfQACvoegBJMFCHqpOCJZRdbLOFy5NgEYBQOJCZB8OpxKC-eRScwsSSVaoAAwyWRybhYzMyYCeYUEFWAojqAEYAAwtBanfGE4QkrAcqTMyR0BktA5YAAeTEI3H4+GAMTg0O54QAwsgoKIKmL2ZlorF4NbFqInshzEc4L8CM5KKI4DB+lg6ixJUSZWSYBT+PJpAAfODa8T4-iDBWo2wOVkVcFQ2EIpE9FV0ZnLVbrXKiYCXOAhNCoYl8FJkQxgMhlXKBcuXMr0RVAA)

**Comment by Oblosys** [comment]
The changes currently on https://github.com/MedFlyt/eslint-plugin-graphql-type-checker/tree/tagged-templates add support for annotation tagged templates, which will give you another way to type standalone queries. You could define a typed tagged template like:

```
const gql = function <TData = Record<string, any>, TVariables = Record<string, any>>(
  literals: string | readonly string[],
  ...args: any[]
): Apollo.TypedDocumentNode<TData, TVariables> {
  return Apollo.gql(literals, ...args)
}
```

And use it everywhere instead of the original `gql`:

```
const greetingQuery = gql<{ greeting: { __typename: 'Greeting'; message: string } }, { language: string }>`#graphql
  query GetGreeting($language: String!) {
    greeting(language: $language) {
      __typename
      message
    }
  }
`
```

The `#graphql` comment is for the GraphQL VSCode extension to recognize the string as GraphQL, as the extension doesn't expect annotations on `gql` tagged templates.

**Comment by Oblosys** [comment]
And will also possible to annotate `useQuery`, or a wrapper function `annotateQuery` (called `Wrap.query` above), as the object is no longer required.
